using System.Collections.Generic;
using ParentalShield.Models;

namespace ParentalShield.Services;

public static class DefaultBlocklists
{
    public static readonly string[] AdultDomains =
    [
        "pornhub.com",
        "xvideos.com",
        "xnxx.com",
        "xhamster.com",
        "redtube.com",
        "youporn.com",
        "spankbang.com",
        "eporner.com",
        "tube8.com",
        "beeg.com",
        "brazzers.com",
        "bangbros.com",
        "naughtyamerica.com",
        "realitykings.com",
        "mofos.com",
        "twistys.com",
        "rk.com",
        "babes.com",
        "teamskeet.com",
        "wicked.com",
        "hustler.com",
        "playboy.com",
        "penthouse.com",
        "dvdadt.com",
        "adulttime.com",
        "heavy-r.com",
        "motherless.com",
        "daftsex.com",
        "empflix.com",
        "tnaflix.com",
        "badjojo.com",
        "thumbzilla.com",
        "hqporner.com",
        "txxx.com",
        "tubepornclassic.com",
        "porntube.com",
        "sunporno.com",
        "porn.com",
        "nuvid.com",
        "vporn.com",
        "cliphunter.com",
        "gotporn.com",
        "voyeurweb.com",
        "palimas.com",
        "pornone.com",
        "czechav.com",
        "erome.com",
        "sex.com",
        "cam4.com",
        "chaturbate.com",
        "stripchat.com",
        "camsoda.com",
        "livejasmin.com",
        "bongacams.com",
        "streamate.com",
        "myfreecams.com",
        "flirt4free.com",
        "imlive.com",
        "cams.com",
        "adultwork.com",
        "jasmin.com",
        "fapchat.com",
        "dirtyroulette.com",
        "chatrandom.com",
        "shagle.com",
        "omegle.adult",
        "onlyfans.com",
        "fansly.com",
        "fanvue.com",
        "loyalfans.com",
        "manyvids.com",
        "iwantclips.com",
        "clips4sale.com",
        "pocketstars.com",
        "fetlife.com",
        "adultfriendfinder.com",
        "passion.com",
        "alt.com",
        "ashleymadison.com",
        "kasidie.com",
        "f95zone.to",
        "rule34.xxx",
        "rule34.paheal.net",
        "e621.net",
        "gelbooru.com",
        "danbooru.donmai.us",
        "nhentai.net",
        "hanime.tv",
        "hentaihaven.xxx",
        "tsumino.com",
        "hitomi.la",
        "pururin.io",
        "fakku.net",
        "simply-hentai.com",
        "luscious.net",
        "exhentai.org",
        "loverslab.com",
        "literotica.com",
        "storiesonline.net",
        "asstr.org"
    ];

    public static readonly string[] GamblingDomains =
    [
        "bet365.com",
        "stake.com",
        "roobet.com",
        "bovada.lv",
        "pokerstars.com",
        "888casino.com",
        "draftkings.com",
        "fanduel.com",
        "betfair.com",
        "williamhill.com",
        "unibet.com",
        "betonline.ag",
        "sportsbet.com.au",
        "ggpoker.com",
        "partypoker.com",
        "ignitioncasino.eu",
        "betmgm.com",
        "rollbit.com",
        "csgoroll.com",
        "hellcase.com",
        "key-drop.com"
    ];

    public static readonly string[] DoHProviders =
    [
        "dns.google",
        "dns.google.com",
        "cloudflare-dns.com",
        "one.one.one.one",
        "dns.quad9.net",
        "dns.nextdns.io",
        "doh.opendns.com",
        "doh.cleanbrowsing.org"
    ];

    public static readonly BlockedApp[] DefaultMatureApps =
    [
        new BlockedApp { Name = "uTorrent", ProcessName = "uTorrent.exe", Category = "18+ / Unmoderated Downloads" },
        new BlockedApp { Name = "BitTorrent", ProcessName = "BitTorrent.exe", Category = "18+ / Unmoderated Downloads" },
        new BlockedApp { Name = "qBittorrent", ProcessName = "qbittorrent.exe", Category = "18+ / Unmoderated Downloads" },
        new BlockedApp { Name = "Omegle Client", ProcessName = "omegle.exe", Category = "Unmoderated Video Chat" },
        new BlockedApp { Name = "Tinder Desktop", ProcessName = "Tinder.exe", Category = "18+ Dating" },
        new BlockedApp { Name = "Grindr", ProcessName = "Grindr.exe", Category = "18+ Dating" },
        new BlockedApp { Name = "Cheat Engine", ProcessName = "cheatengine-x86_64.exe", Category = "Exploits & Tampering" }
    ];
}
